# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://here-now.us
title: HereNow
email: info@here-now.us
author: Jeff Hammerquist
description: "HereNow is a dynamic signage solution that brings discovery and delight to the travel experience by reconnecting people with place."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: contact us
    type: envelope
    url: mailto:info@here-now.us?subject=Tell me more!
  - title: github
    type: github
    url: https://github.com/project-monolith
