# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://placestation.io
title: placeStation
email: info@placeStation.io
author: Your Name
description: "placeStation is an Open Source kiosk frontend for OneBusAway, designed to help transit riders connect to the place around them as they get where they're going."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: contact us
    url: mailto:info@placestation.io?subject=Tell me more!
  - title: github
    url: https://github.com/project-monolith
